CONFIG_CODE = 'social_auth_config'
DEFAULT_BACKEND_CODE = 'default_backend'
SOCIAL_STRATEGY_CODE = 'social_strategy'
SOCIAL_STORAGE_CODE = 'social_storage'
EXCHANGE_REDIRECT_URI_CODE = 'exchange_redirect_uri'
